data_dir: /kaggle/input/spinach-leaf-area/spinach
test_images_dir: test_images
results_dir: results/deeplabv3plus
models_dir: save/models
batch_size: 4
num_epochs: 10
learning_rate: 0.0001
num_classes: 3
num_workers: 4
early_stopping:
  patience: 5
  delta: 0.0005
transformations:
  horizontal_flip_p: 0.5
  random_rotate_p: 0.5
  elastic_transform_p: 0.3
  grid_distortion_p: 0.3
  # normalize_mean: [0.485, 0.456, 0.406]
  # normalize_std: [0.229, 0.224, 0.225]
loss:
  smooth: 0.00001
  class_weights: [0.1, 1.0, 5.0]
  dice_ce_weights: [0.5, 0.5]
  ignore_index: null